name: NFTs Gallery CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install  NPM 
      run: npm install
    - name: Run Unit Tests
      run: npm test

  deploy:

    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Firebase Function
        uses: danielmillan/pipelines-firebase-functions@1.0.1
        with:
          # Token generated to authenticate in firebase
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          # Name of the folder containing the resources to be deployed
          resources-name: build
          # Firebase project name
          project-name: NFTs Gallery
