name: NFTs Gallery CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install  NPM 
      run: npm install
    - name: Run Unit Tests
      run: npm test

  deploy:

    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
